name: install-dpctl
description: Clone and build DPCTL
inputs:
  DPCTL_URL:
    description: URL of the DPCTL repository to use.
  DPCTL_BRANCH:
    description: Name of the DPCTL branch to use.
  DPCTL_PATH:
    description: Path where to put DPCTL
  DPCPP_PATH:
    description: Path to DPC++
  VENV_PATH:
    description: Path to virtualenv

runs:
  using: "composite"
  steps:
    - name: Clone and install DPCTL
      shell: bash
      run: |
        export DPCTL_PATH=${{ inputs.DPCTL_PATH }}
        git clone --depth=1 --branch ${{ inputs.DPCTL_BRANCH }} ${{ inputs.DPCTL_URL }} $DPCTL_PATH
        pushd $DPCTL_PATH
        source ${{ inputs.VENV_PATH }}/bin/activate
        export DPCPP_PATH=${{ inputs.DPCPP_PATH }}
        export PATH=$DPCPP_PATH/bin:$PATH
        export LD_LIBRARY_PATH=$DPCPP_PATH/lib:$LD_LIBRARY_PATH
        pip install --no-cache-dir numpy cython scikit-build cmake ninja pytest versioneer
        python scripts/build_locally.py --c-compiler=$DPCPP_PATH/bin/clang \
          --cxx-compiler=$DPCPP_PATH/bin/clang++ \
          --compiler-root=$DPCPP_PATH/bin \
          --cmake-opts="-DCMAKE_INCLUDE_PATH=/lib/x86_64-linux-gnu"
