name: "SYCL Intel PVC Test"

on:
  push:
    branches: [ "sycl-develop", "test_release_compiler"]
  pull_request:
    branches: [ "sycl-develop" ]
  merge_group:
    branches: [ "sycl-develop" ]
  workflow_dispatch:
    inputs:
      DPCPP_VERSION:
        description: "DPCPP version to use"
        type: string

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    strategy:
      matrix:
        compiler: [ NIGHTLY, RELEASE ]
    name: Run Intel PVC tests
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: sudo apt update && sudo apt install -y cmake ninja-build
      # For a specific DPC++ nightly build define the repository variable DPCPP_VERSION
      # for example using the tag: 'nightly-2024-04-22'
      - name: Install DPC++
        uses: ./.github/actions/install-dpcpp
        with:
          DPCPP_RELEASE: ${{ matrix.compiler }}
          DPCPP_VERSION: ${{ inputs.DPCPP_VERSION }}
      - name: Build
        shell: bash
        run: |
          . setvars.sh
          # Persist environment variables to following steps
          env >> $GITHUB_ENV
          which clang++
          clang++ --version
          cmake -G Ninja  \
            -DCUTLASS_ENABLE_SYCL=ON \
            -DDPCPP_SYCL_TARGET=intel_gpu_pvc
          cmake --build .

      - name: Unit test
        shell: bash
        run: |
          which clang++
          cmake --build . --target test_unit -j 24

      - name: Examples
        shell: bash
        run: |
          cmake --build . --target test_examples -j 24
