name: "SYCL Intel PVC Test"

on:
  push:
    branches: [ "sycl-develop" ]
  pull_request:
    branches: [ "sycl-develop" ]
  merge_group:
    branches: [ "sycl-develop" ]
  workflow_dispatch:
    inputs:
      DPCPP_VERSION:
        description: "DPCPP version to use"
        type: string

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Intel PVC tests
    runs-on: cp-gpumax-1100-gpu
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      # For a specific DPC++ nightly build define the repository variable DPCPP_VERSION
      # for example using the tag: 'nightly-2024-04-22'
      - name: Install DPC++
        id: install_dpcpp
        uses: ./.github/actions/install-dpcpp
        with:
          DPCPP_VERSION: ${{ inputs.DPCPP_VERSION }}
          DPCPP_PATH: ~/dpcpp
      - name: Build
        shell: bash
        run: |
          export DPCPP_PATH=~/dpcpp
          export PATH=$DPCPP_PATH/bin/:$PATH
          export C_INCLUDE_PATH=$DPCPP_PATH/include/:$C_INCLUDE_PATH
          export CPLUS_INCLUDE_PATH=$DPCPP_PATH/include/:$CPLUS_INCLUDE_PATH
          export LD_LIBRARY_PATH=$DPCPP_PATH/lib/:$LD_LIBRARY_PATH
          export CC=clang
          export CXX=clang++
          clang++ --version
          cmake -G Ninja  \
            -DCUTLASS_ENABLE_SYCL=ON \
            -DDPCPP_SYCL_TARGET=intel_gpu_pvc
          cmake --build .

      - name: Unit test
        shell: bash
        run: |
          export DPCPP_PATH=~/dpcpp
          export LD_LIBRARY_PATH=$DPCPP_PATH/lib/:$LD_LIBRARY_PATH
          cmake --build . --target test_unit -j 24

      - name: Examples
        shell: bash
        run: |
          export DPCPP_PATH=~/dpcpp
          export LD_LIBRARY_PATH=$DPCPP_PATH/lib/:$LD_LIBRARY_PATH
          cmake --build . --target test_examples -j 24
